- platform: mjpeg
  mjpeg_url: http://192.168.45.230:80/Streaming/Channels/2/preview
  name: Deck
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.45.231:80/Streaming/Channels/2/preview
  name: Front Door
  username: admin
  password: !secret hik_pwd
# - platform: mjpeg
#   mjpeg_url: http://192.168.45.232:80/Streaming/Channels/2/preview
#   name: Garage
#   username: admin
#   password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.45.233:80/Streaming/Channels/2/preview
  name: Driveway
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.45.235:80/Streaming/Channels/2/preview
  name: Daisy
  username: admin
  password: !secret hik_pwd
- platform: doorbird
