homeassistant:
  name: Reeder
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_tz
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp

cloud:
  google_actions:
    filter:
      include_entities:
        - climate.basement_thermostat
        - climate.main_thermostat
        - climate.upstairs_thermostat
        - climate.garage_thermostat
      include_domains:
        - light
        - switch
      exclude_domains:
        - group
        - input_boolean
        - scene
        - script
        - cover
        - media_player
        - climate
  alexa:
    filter:
      include_entities:
        - climate.basement_thermostat
        - climate.main_thermostat
        - climate.upstairs_thermostat
        - climate.garage_thermostat
      include_domains:
        - light
        - switch
      exclude_domains:
        - group
        - input_boolean
        - scene
        - script
        - cover
        - media_player
        - climate

http:
updater:
  reporting: false
tts:
  - platform: google_translate
    service_name: google_say
recorder:
  db_url: !secret url_db
  purge_keep_days: 3

system_health:

influxdb:
  host: localhost
  username: !secret influx_usr
  password: !secret influx_pwd
  database: !secret influx_db
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - device_tracker
      - lock
    entities:
      - switch.equipment_room_recirculation_pump
      - switch.water_main_shut_off
  
weather:
  - platform: darksky
    api_key: !secret darksky_api

elkm1:
  host: !secret url_elk
  temperature_unit: F
  area:
    exclude: [2-8]
  zone:
    exclude: [17-24, 27-32, 37-208]
  output:
    exclude: [1-8, 11-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-5]
  task:
    include: [1-4]
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

doorbird:
  devices:
    - host: !secret db_ip
      username: !secret db_usr
      password: !secret db_pwd
      token: !secret db_token
      hass_url_override: !secret hass_ip
      name: Front Door

lutron:
  host: !secret rr_ip
  username: !secret rr_usr
  password: !secret rr_pwd

water_heater:
  - platform: econet
    username: !secret econet_user
    password: !secret econet_pwd

device_tracker:
  - platform: unifi
    host: !secret unifi_ip
    verify_ssl: false
    username: !secret unifi_usr
    password: !secret unifi_pwd
    ssid_filter:
      - 'ReedingRainbow'
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

scene:
  platform: hunterdouglas_powerview
  address: !secret powerview_ip

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

owntracks:
  max_gps_accuracy: 100

####################################################
#                     Includes                     #
####################################################
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
climate: !include climate.yaml
automation: !include automation.yaml
group: !include groups.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
camera: !include cameras.yaml
rest_command: !include rest_commands.yaml
input_boolean: !include input_boolean.yaml
timer: !include timers.yaml
zone: !include zones.yaml

logger:
  default: info

history:
sun:
conversation:
logbook:
frontend:
  themes: !include_dir_merge_named themes/
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

lovelace:
  mode: yaml
config:
hassio:
map:
discovery:
  ignore:
    - axis
    - plex_mediaserver
    - igd
stream:

panel_iframe:
  grafana:
    title: 'Grafana'
    url: 'http://192.168.45.249:3000'
    icon: mdi:chart-timeline
  zwave2mqtt:
    title: Z-Wave to MQTT
    icon: mdi:z-wave
    url: http://192.168.45.249:8091
