name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
#       - name: Checking out awesomeness from GitHub
#         uses: actions/checkout@v1.0.0
#       - name: Running the awesome linter
#         uses: max/awesome-lint@v2.0.0
#         with:
#           filename: README.md
#     - name: Secret Scan
#       uses: max/secret-scan@1.0.0
#       - uses: actions/checkout@v1
      - name: HA Check
        uses: "docker://homeassistant/home-assistant:latest"
        run: |
          python -m homeassistant --version
