name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: HA Check
        uses: "docker://homeassistant/home-assistant:latest"
        with:
          args: python -m homeassistant --version
